apiVersion: v1
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0"
    elasticsearch.hosts: [ "http://elasticsearch:9200" ]
    monitoring.ui.container.elasticsearch.enabled: true
    elasticsearch.username: "kibana"
    elasticsearch.password: "oLTg0SsVOfFglU6GsxBr"

kind: ConfigMap
metadata:
  labels:
    app: kibana
  name: kibana-config
  namespace: logging
